/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.apalopta.treekt.kotlin-application-conventions")
}

dependencies {
//    implementation("org.apache.commons:commons-text")
//    implementation(project(":utilities"))
    implementation("org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.2")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

version = "0.1.0"

application {
    // Define the main class for the application.
    mainClass.set("de.apalopta.treekt.MainKt")
}
